version: '3.8'

services:
  dwarf-fortress:
    build: .
    platform: linux/amd64  # Force x86_64 architecture for Dwarf Fortress
    container_name: dwarf-fortress-ai
    privileged: true  # Allow dfhack to use setarch
    ports:
      - "8080:8080"  # API server for dashboard integration
      - "5900:5900"  # VNC server
      - "5901:5901"  # NoMachine remote desktop access
    volumes:
      - ./saves:/opt/dwarf-fortress/df/data/save    # Mount saves directory
      - ./logs:/opt/dwarf-fortress/df/stderr.txt    # Mount logs for AI analysis
      - ./output:/opt/dwarf-fortress/output:Z       # Output directory for AI analysis (with SELinux context)
      - ./vnc-config:/home/dfuser/.vnc              # Mount VNC configuration directory
    environment:
      - DISPLAY=:99
    stdin_open: true    # Keep STDIN open for interactive use
    tty: true          # Allocate a pseudo-TTY
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Xvfb"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy-fortress
    ports:
      - "4000:80"      # Dashy web interface
    volumes:
      - ./dashy-conf.yml:/app/public/conf.yml:ro   # Dashboard configuration
    environment:
      - NODE_ENV=production
    depends_on:
      - dwarf-fortress
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  web-manager:
    build:
      context: .
      dockerfile: Dockerfile.webmanager
    container_name: df-web-manager
    ports:
      - "3000:3000"    # Web management interface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw  # Docker socket for container management (rw for commands)
      - .:/app/project:ro                              # Project files for management
      - ./templates:/app/templates:ro                  # Template files
      - ./static:/app/static:ro                        # Static files
    environment:
      - FLASK_ENV=production
      - PROJECT_PATH=/app/project
    depends_on:
      - dwarf-fortress
      - dashy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    # Resource limits for the web manager
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  df_saves:
    driver: local
  df_logs:
    driver: local